In [2]:
import numpy as np

**Initialize an empty array with size 2×2**

In [ ]:
arr_empty = np.empty((2, 2))
print(arr_empty)

[[7.20414944e-316 0.00000000e+000]
 [1.03867630e-152 6.20311190e+223]]


**Initialize an all-ones array with size 4×2**

In [ ]:
arr_ones = np.ones((4, 2))
print(arr_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**Return a new array of given shape and type, filled with fill value**

In [ ]:
arr_full = np.full((3, 3), fill_value=7)
print(arr_full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


**Return a new array of zeros with same shape and type as a given array**

In [ ]:
original = np.array([[1, 2, 3],
                     [4, 5, 6]])

arr_zeros_like = np.zeros_like(original)
print(arr_zeros_like)

[[0 0 0]
 [0 0 0]]


**Return a new array of ones with same shape and type as a given array**

In [ ]:
arr_ones_like = np.ones_like(original)
print(arr_ones_like)

[[1 1 1]
 [1 1 1]]


**Convert a existing Python list to a NumPy array**

In [ ]:
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print(np_array)

[1 2 3 4]


**Create an array with values from 10 to 49**

In [6]:
import numpy as np
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Create a 3×3 matrix with values from 0 to 8**

In [7]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Create a 3×3 identity matrix**

In [8]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Create a random array of size 30 and find the mean**

In [9]:
rand_arr = np.random.random(30)
mean_value = rand_arr.mean()

print(rand_arr)
print("Mean:", mean_value)

[0.08046174 0.6387646  0.72020005 0.49667579 0.88039781 0.06615771
 0.38853253 0.07602296 0.69916981 0.3803164  0.37200862 0.40127845
 0.04141386 0.48834727 0.53185119 0.47634638 0.55146871 0.47178102
 0.41621166 0.18246959 0.59500631 0.38686789 0.40393378 0.54492264
 0.55841525 0.60195801 0.80835    0.11145318 0.60992161 0.44050568]
Mean: 0.44737368197668886


**Create a 10×10 random array and find min & max**

In [10]:
rand_10x10 = np.random.random((10, 10))

min_val = rand_10x10.min()
max_val = rand_10x10.max()

print("Min:", min_val)
print("Max:", max_val)

Min: 0.016028704284968387
Max: 0.9897909221886912


**Create a zero array of size 10 and replace 5th element with 1**

In [11]:
arr_zero = np.zeros(10)
arr_zero[4] = 1
print(arr_zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**Reverse an array**

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


**Create a 2D array with 1 on the border and 0 inside**

In [12]:
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print(border_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Create an 8×8 checkerboard pattern**

In [13]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Add the two arrays (x + y)**

In [14]:
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])
add_xy = x + y
print(add_xy)

[[ 6  8]
 [10 13]]


**Subtract the two arrays (x – y)**

In [ ]:
sub_xy = x - y
print(sub_xy)

[[-4 -4]
 [-4 -3]]


**Multiply the array with any integer**

In [15]:
mul_x = 3 * x
print(mul_x)

[[ 3  6]
 [ 9 15]]


**Find the square of each element in array x**

In [16]:
square_x = x ** 2
print(square_x)

[[ 1  4]
 [ 9 25]]


**Dot products**

In [17]:
dot_vw = np.dot(v, w)
print(dot_vw)


219


In [18]:
dot_xv = np.dot(x, v)
print(dot_xv)

[29 77]


In [19]:
dot_xy = np.dot(x, y)
print(dot_xy)

[[19 22]
 [50 58]]


**Concatenate x and y along rows**

In [20]:
concat_xy_row = np.concatenate((x, y), axis=0)
print(concat_xy_row)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


**Concatenate v and w along columns**

In [21]:
concat_vw_col = np.column_stack((v, w))
print(concat_vw_col)


[[ 9 11]
 [10 12]]


**Try to concatenate x and v → Why error?**

In [7]:
np.concatenate((x, v), axis=0)
# It throws valueError because all the input arrays must have same number of
# dimensions, but the array at index 0 is 2D and the array at index 1 is 1D


NameError: name 'x' is not defined

**Prove: A.A-1=I**

In [3]:
A = np.array([[3, 4], [7, 8]])

B = np.array([[5, 3],[2, 1]])

A_inv = np.linalg.inv(A)
I = A @ A_inv
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


**AB/=BA**

In [4]:
AB = A @ B
BA = B @ A
print("AB = \n", AB)
print("BA = \n", BA)

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]


**(AB)^T = B^T.A^T**

In [5]:
left = (A @ B).T
right = B.T @ A.T

print("Left = \n", left)
print("Right = \n", right)

Left = 
 [[23 51]
 [13 29]]
Right = 
 [[23 51]
 [13 29]]


**Solve System of Linear Equations using Inverse Method**

2x-3y+z = -1x-y+2z = -3 3x+y-z = 9

In [6]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])
A_inv = np.linalg.inv(A)
X = A_inv @ B
print(X)

[ 2.  1. -2.]
